[package]
name = "bootty-mux"
edition.workspace = true
version.workspace = true

[features]
default = ["app"]
app = [
  "dep:bootty-runtime",
  "dep:bootty-surface",
  "dep:bootty-terminal",
  "dep:derive_more",
]

[dependencies]
bootty-mux-model = { path = "../bootty-mux-model" }
bootty-write = { path = "../bootty-write" }
anyhow.workspace = true
derive_more = { workspace = true, optional = true }
inventory.workspace = true
serde.workspace = true
strum.workspace = true
bootty-runtime = { path = "../bootty-runtime", optional = true }
bootty-surface = { path = "../bootty-surface", optional = true }
bootty-terminal = { path = "../bootty-terminal", optional = true }

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
