[package]
name = "bootty-ui"
edition.workspace = true

[dependencies]
eframe.workspace = true
egui_code_editor.workspace = true
iconflow.workspace = true
bootty-item = { path = "../bootty-item" }
bootty-workspace-hack = { version = "0.1", path = "../bootty-workspace-hack" }

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { workspace = true, features = ["wayland", "x11"] }

[dev-dependencies]
pretty_assertions.workspace = true
proptest.workspace = true
rstest.workspace = true
