[package]
name = "bootty-zellij"
version.workspace = true
edition.workspace = true

[features]
default = ["app"]
app = ["bootty-mux/app", "bootty-remote/app"]

[dependencies]
anyhow.workspace = true
bootty-identity = { path = "../bootty-identity" }
bootty-mux = { path = "../bootty-mux", default-features = false }
bootty-mux-model = { path = "../bootty-mux-model" }
bootty-remote = { path = "../bootty-remote", default-features = false }
inventory.workspace = true
rmux-ipc.workspace = true
bootty-workspace-hack = { version = "0.1", path = "../bootty-workspace-hack" }

[lints]
workspace = true
