[package]
name = "bootty"
version.workspace = true
edition.workspace = true
build = "build.rs"

[features]
bootty-dev = ["bootty-app/bootty-dev", "bootty-cli/bootty-dev", "bootty-control/bootty-dev"]

[[bin]]
name = "bootty"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
bootty-app = { path = "../bootty-app" }
bootty-cli = { path = "../bootty-cli" }
bootty-command = { path = "../bootty-command" }
bootty-control = { path = "../bootty-control" }
bootty-identity = { path = "../bootty-identity" }
bootty-herdr = { path = "../bootty-herdr" }
bootty-mux = { path = "../bootty-mux" }
bootty-native = { path = "../bootty-native" }
bootty-remote = { path = "../bootty-remote" }
bootty-rmux = { path = "../bootty-rmux" }
bootty-tmux = { path = "../bootty-tmux" }
serde_json.workspace = true
clap.workspace = true
thiserror.workspace = true
bootty-workspace-hack = { version = "0.1", path = "../bootty-workspace-hack" }

[build-dependencies]
embed-resource.workspace = true

[dev-dependencies]
assert_fs.workspace = true
bootty-config = { path = "../bootty-config" }
bootty-extension = { path = "../bootty-extension" }
bootty-render = { path = "../bootty-render" }
egui.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true

[lints]
workspace = true
