[package]
name = "bootty-runtime"
edition.workspace = true
autobenches = false

[dependencies]
anyhow.workspace = true
bootty-surface = { path = "../bootty-surface" }
bootty-terminal = { path = "../bootty-terminal" }
portable-pty.workspace = true

[[bench]]
name = "pty_drain"
harness = false

[[bench]]
name = "flood_response"
harness = false

[dev-dependencies]
assert_fs.workspace = true
criterion.workspace = true
pretty_assertions.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
