[package]
name = "bootty-write"
edition.workspace = true

[lints]
workspace = true

[dependencies]
tempfile.workspace = true
bootty-workspace-hack = { version = "0.1", path = "../bootty-workspace-hack" }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Storage_FileSystem"] }
